service: nestjs-serverless-pg
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  memorySize: 128
  logRetentionInDays: 1
  timeout: 30

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-express
  - serverless-offline

        
      
      
