service: nestjs-serverless-pg
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  httpApi:
    cors: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-express
  - serverless-offline